spring:
  application:
    name: user_management_api

  datasource:
    url: jdbc:postgresql://srv-alex:5432/user_management_api_db_java
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update # use "none", "validate", "update", "create", "create-drop" conforme o ambiente
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 9090

debug: true